version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'thursday'
      time: '10:10'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'thursday'
      time: '09:10'
      timezone: 'Asia/Tokyo'
